AWSTemplateFormatVersion: '2010-09-09'
Resources:
  UnittestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 's3dbunittestbucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  UnittestBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref UnittestBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'DenyPublicReadACL'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${UnittestBucket}/*'
            Condition:
              StringEquals:
                's3:x-amz-acl': ['public-read', 'public-read-write', 'authenticated-read']
          - Sid: 'DenyPublicReadGrant'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${UnittestBucket}/*'
            Condition:
              StringLike:
                's3:x-amz-grant-read': '*'
  UnittestKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: 'KMS key for S3DB unit tests'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Enable IAM User Permissions'
            Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
  UnittestKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: 'alias/s3db-unittest-key'
      TargetKeyId: !Ref UnittestKMSKey